dist: bionic
language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_script:
  - scripts-ci/prepare-for-code-coverage.sh
  - scripts-ci/start-services-in-background.sh &
  - scripts-ci/wait-for-ports.sh
script:
  - scripts-ci/run-tests.sh
after_script:
  - scripts-ci/collect-code-coverage.sh
deploy:
  provider: script
  script: scripts-ci/deploy.sh
