dist: bionic
language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_script:
  - scripts-ci/prepare-for-code-coverage.sh
  - scripts-ci/build-and-start-services-in-background.sh &
  - scripts-ci/wait-for-ports.sh
script:
  - scripts-ci/run-tests.sh
after_script:
  - scripts-ci/collect-code-coverage.sh

deploy:
  - provider: s3
    skip_cleanup: true
    local_dir: build-git-master
    region: eu-west-1
    bucket: "git-master.sequencediagram.io"
    cache_control: "max-age=300"
    acl: public_read
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    local_dir: build-git-master/static
    region: eu-west-1
    bucket: "git-master.sequencediagram.io"
    upload-dir: static
    cache_control: "max-age=3600"
    acl: public_read
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    local_dir: build-prod
    region: eu-west-1
    bucket: "sequencediagram.io"
    cache_control: "max-age=1800"
    acl: public_read
    on:
      tags: true
  - provider: s3
    skip_cleanup: true
    local_dir: build-prod/static
    region: eu-west-1
    bucket: "sequencediagram.io"
    upload-dir: static
    cache_control: "max-age=604800"
    acl: public_read
    on:
      tags: true

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: scripts-ci/deploy.sh
#  on:
#    branch: master
